name: build-dgraph

on:
  push:
    branches:
      - dgraph-personal

jobs:
  
  build-dgraph:
    runs-on: ubuntu-18.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v2.1.5
        with:
          go-version: '^1.13.1' 

      - name: Install dgraph dependencies
        run: sudo apt-get update; sudo apt-get install gcc make

      - name: Check Go installed
        run: go version

      - name: Checkout dgraph
        uses: actions/checkout@v2
        with:
          repository: unigraph-dev/dgraph.git
          ref: dgraph-personal

      - name: Install dgraph linux
        run: cd ./dgraph; make install; ls $(go env GOPATH)/bin | grep dgraph;

      - name: Install dgraph macOS
        run: GOOS=darwin make install; ls $(go env GOPATH)/bin | grep darwin_amd64;

      - name: Install dgraph windows
        run: GOOS=windows make install; ls $(go env GOPATH)/bin | grep windows_amd64 

      - name: Move dgraph builds to ~/dist
        run: mkdir ~/dist && mv $(go env GOPATH)/bin/* ~/dist

      - name: Upload linux build as artifact
        uses: actions/upload-artifact@v2
        with:
          name: dgraph_linux_amd64
          path: ~/dist/dgraph
          if-no-files-found: error 

      - name: Upload macOS build as artifact
        uses: actions/upload-artifact@v2
        with:
          name: dgraph_darwin_amd64
          path: ~/dist/darwin_amd64
          if-no-files-found: error 

      - name: Upload Windows build as artifact
        uses: actions/upload-artifact@v2
        with:
          name: dgraph_windows_amd64
          path: ~/dist/windows_amd64
          if-no-files-found: error 